name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Release to Maven
          uses: qcastel/github-actions-maven-release@master
          with:
            release-branch-name: "release"

            gpg-enabled: "true"
            gpg-key-id: "someKeyId"
            gpg-key: ${{ secrets.gpg_private_key }}
            gpg-passphrase: ${{ secrets.gpg_passphrase }}

            maven-repo-server-id: ${{ secrets.nexus_username }}
            maven-repo-server-username: ${{ secrets.nexus_username }}
            maven-repo-server-password: ${{ secrets.nexus_password }}

            maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"

            git-release-bot-name: "release-bot"
            git-release-bot-email: "release-bot@example.com"

            access-token: ${{ secrets.GITHUB_TOKEN }}
